import { PartnerCreator } from "./types";

export const partnerCreatorsData: PartnerCreator[] = [
  {
    id: "jacksons-ai",
    name: "Jacksons AI",
    handle: "@Jacksons_ai",
    email: "jackson@jacksonsai.com",
    avatar: "/creator4.png",
    bannerImage: null,
    bannerText: "CREATE & MONETIZE",
    bannerBg: "bg-[#dcdcd4] text-[#111111]",
    subscribers: "624K",
    videosCount: "25",
    bio: "Hey, I'm Jackson. I've been doing YouTube automation for over 5 years, making mistakes, fixing them, and figuring out what actually works to scale channels with cutting edge AI tools.",
    channelUrl: "https://youtube.com/@jacksons_ai",
    recentVideos: [
      {
        id: "v1",
        title: "Pixverse Integration",
        thumbnail: "/home1.png",
        views: "2.2m views",
        publishedAt: "3 weeks ago",
        url: "https://youtube.com/@jacksons_ai",
      },
      {
        id: "v2",
        title: "Kling Integration",
        thumbnail: "/home2.png",
        views: "2.2m views",
        publishedAt: "3 weeks ago",
        url: "https://youtube.com/@jacksons_ai",
      },
      {
        id: "v3",
        title: "Kling Integration II",
        thumbnail: "/home3.png",
        views: "2.2m views",
        publishedAt: "3 weeks ago",
        url: "https://youtube.com/@jacksons_ai",
      },
    ],
    collaborations: [
      { name: "Higgsfield", logo: "/brand-1.png" },
      { name: "ElevenLabs", logo: "/brand-2.png" },
      { name: "movavi", logo: "/brand-3.png" },
      { name: "MusicGPT", logo: "/brand-4.png" },
      { name: "Hailuo AI", logo: "/brand-5.png" },
    ],
  },
  {
    id: "techsavvy",
    name: "TechSavvy",
    handle: "@TechSavvyYT",
    email: "contact@techsavvy.io",
    avatar: "/creator1.png",
    bannerImage: null,
    bannerText: "ALL ABOUT MONEY",
    bannerBg: "bg-gradient-to-r from-emerald-950 via-black to-emerald-900 text-lime-400",
    subscribers: "320K",
    videosCount: "15",
    bio: "Welcome to TechSavvy! Here, I explore the latest in tech trends, gadgets, and software tips to help you get the most out of your devices. Join me for in-depth reviews and tutorials.",
    channelUrl: "https://youtube.com/@cybercashcoach",
    recentVideos: [
      {
        id: "v4",
        title: "ChatGPT Automation Workflow",
        thumbnail: "/home4.png",
        views: "1.8m views",
        publishedAt: "2 weeks ago",
        url: "https://youtube.com/@cybercashcoach",
      },
      {
        id: "v5",
        title: "Top 10 AI Tools You Need",
        thumbnail: "/home5.png",
        views: "950K views",
        publishedAt: "1 month ago",
        url: "https://youtube.com/@cybercashcoach",
      },
      {
        id: "v6",
        title: "Scale Content with AI Agents",
        thumbnail: "/home6.png",
        views: "600K views",
        publishedAt: "2 months ago",
        url: "https://youtube.com/@cybercashcoach",
      },
    ],
    collaborations: [
      { name: "ElevenLabs", logo: "/brand-2.png" },
      { name: "Higgsfield", logo: "/brand-1.png" },
      { name: "movavi", logo: "/brand-3.png" },
      { name: "Hailuo AI", logo: "/brand-5.png" },
    ],
  },
  {
    id: "cookingwithclara",
    name: "CookingWithClara",
    handle: "@CookingWithClara",
    email: "clara@cookingwithclara.com",
    avatar: "/creator3.png",
    bannerImage: null,
    bannerText: "VIDEO CREATION TIPS",
    bannerBg: "bg-gradient-to-r from-zinc-900 via-zinc-800 to-black text-white",
    subscribers: "850K",
    videosCount: "42",
    bio: "Hi, I'm Clara! I love sharing my passion for cooking with you all. From easy weeknight dinners to elaborate holiday feasts, my channel is packed with recipes and cooking hacks that will inspire.",
    channelUrl: "https://youtube.com/@emmiescalm",
    recentVideos: [
      {
        id: "v7",
        title: "AI Recipe Generator Test",
        thumbnail: "/home7.png",
        views: "1.2m views",
        publishedAt: "1 week ago",
        url: "https://youtube.com/@emmiescalm",
      },
      {
        id: "v8",
        title: "Mastering AI Kitchen Prep",
        thumbnail: "/home8.png",
        views: "780K views",
        publishedAt: "3 weeks ago",
        url: "https://youtube.com/@emmiescalm",
      },
      {
        id: "v9",
        title: "Smart Cooking Hacks 2026",
        thumbnail: "/home9.png",
        views: "1.5m views",
        publishedAt: "1 month ago",
        url: "https://youtube.com/@emmiescalm",
      },
    ],
    collaborations: [
      { name: "movavi", logo: "/brand-3.png" },
      { name: "MusicGPT", logo: "/brand-4.png" },
      { name: "Hailuo AI", logo: "/brand-5.png" },
    ],
  },
  {
    id: "bakingwithbenji",
    name: "BakingWithBenji",
    handle: "@BakingWithBenji",
    email: "benji@bakingwithbenji.com",
    avatar: "/creator6.png",
    bannerImage: null,
    bannerText: "AI Guide with Mark",
    bannerBg: "bg-gradient-to-r from-amber-950 via-zinc-900 to-black text-amber-400",
    subscribers: "1.2M",
    videosCount: "42",
    bio: "Hello, I'm Benji! I'm passionate about baking and love sharing creative dessert recipes and tips. Whether you're a beginner or a pro, my channel offers sweet inspiration and easy-to-follow tutorials.",
    channelUrl: "https://youtube.com/@markaiguy",
    recentVideos: [
      {
        id: "v10",
        title: "3D Pastry Design AI",
        thumbnail: "/home2.png",
        views: "3.1m views",
        publishedAt: "2 weeks ago",
        url: "https://youtube.com/@markaiguy",
      },
      {
        id: "v11",
        title: "Sweet Science: AI in Baking",
        thumbnail: "/home4.png",
        views: "1.9m views",
        publishedAt: "1 month ago",
        url: "https://youtube.com/@markaiguy",
      },
      {
        id: "v12",
        title: "Top 5 AI Baking Secrets",
        thumbnail: "/home6.png",
        views: "2.4m views",
        publishedAt: "2 months ago",
        url: "https://youtube.com/@markaiguy",
      },
    ],
    collaborations: [
      { name: "Higgsfield", logo: "/brand-1.png" },
      { name: "ElevenLabs", logo: "/brand-2.png" },
      { name: "MusicGPT", logo: "/brand-4.png" },
    ],
  },
];
